# Generated by Django 4.2.16 on 2025-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_quiz_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="option_a",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="option_b",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="option_c",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="option_d",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(max_length=1),
        ),
    ]
